apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: secondary-network
  namespace: web-server
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br1",
    "ipam": {
      "type": "host-local",
      "subnet": "192.168.50.0/24",
      "rangeStart": "192.168.50.100",
      "rangeEnd": "192.168.50.200",
      "routes": [{"dst": "0.0.0.0/0"}],
      "gateway": "192.168.50.1"
    }
  }'
