{{- if and .Values.backup.enabled .Values.backup.internal.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mysql-local-backup
  namespace: {{ .Values.namespaces.database }}
  labels:
    app: mysql-backup
spec:
  schedule: {{ .Values.backup.internal.schedule | quote }}
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mysql-backup
        spec:
          restartPolicy: OnFailure
          containers:
          - name: backup
            image: {{ .Values.backup.internal.image.repository }}:{{ .Values.backup.internal.image.tag }}
            command:
            - sh
            - -c
            - |
              TIMESTAMP=$(date +%F-%H-%M-%S)

              mysqldump -h {{ .Release.Name }}-mysql-primary.{{ .Values.namespaces.database }} \
                -uroot -p$MYSQL_ROOT_PASSWORD \
                --all-databases \
                | gzip > /backup/backup-$TIMESTAMP.sql.gz

              # keep only last {{ .Values.backup.internal.retention }} backups
              ls -tp /backup/backup-*.sql.gz 2>/dev/null | tail -n +{{ add1 (atoi .Values.backup.internal.retention) }} | while read f; do rm -f "$f"; done || true
            env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mysql.auth.existingSecret }}
                  key: mysql-root-password
            volumeMounts:
            - name: backup-volume
              mountPath: /backup
          volumes:
          - name: backup-volume
            persistentVolumeClaim:
              claimName: {{ .Values.backup.pvc.name }}
{{- end }}
