{{- if .Values.podWatcher.enabled }}
{{- if .Values.podWatcher.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.podWatcher.serviceAccount.name }}
  namespace: {{ .Values.podWatcher.namespace }}
{{- end }}
---
{{- if .Values.podWatcher.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.podWatcher.rbac.clusterRole.name }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.podWatcher.rbac.clusterRoleBinding.name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.podWatcher.rbac.clusterRole.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.podWatcher.serviceAccount.name }}
  namespace: {{ .Values.podWatcher.namespace }}
{{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.podWatcher.name }}
  namespace: {{ .Values.podWatcher.namespace }}
spec:
  replicas: {{ .Values.podWatcher.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.podWatcher.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.podWatcher.name }}
    spec:
      serviceAccountName: {{ .Values.podWatcher.serviceAccount.name }}
      containers:
      - name: controller
        image: {{ .Values.podWatcher.image.repository }}:{{ .Values.podWatcher.image.tag }}
        imagePullPolicy: {{ .Values.podWatcher.image.pullPolicy }}
        resources:
          requests:
            memory: {{ .Values.podWatcher.resources.requests.memory | quote }}
            cpu: {{ .Values.podWatcher.resources.requests.cpu | quote }}
          limits:
            memory: {{ .Values.podWatcher.resources.limits.memory | quote }}
            cpu: {{ .Values.podWatcher.resources.limits.cpu | quote }}
{{- end }}