{{- if .Values.secondaryNetwork.enabled }}
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: {{ .Values.secondaryNetwork.name }}
  namespace: {{ .Values.namespaces.webServer }}
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "{{ .Values.secondaryNetwork.type }}",
      "master": "{{ .Values.secondaryNetwork.master }}",
      "mode": "{{ .Values.secondaryNetwork.mode }}",
      "ipam": {
        "type": "{{ .Values.secondaryNetwork.ipam.type }}",
        "subnet": "{{ .Values.secondaryNetwork.ipam.subnet }}",
        "rangeStart": "{{ .Values.secondaryNetwork.ipam.rangeStart }}",
        "rangeEnd": "{{ .Values.secondaryNetwork.ipam.rangeEnd }}",
        "gateway": "{{ .Values.secondaryNetwork.ipam.gateway }}"
      }
    }
{{- end }}
