apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-backup
  namespace: database
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
  